layout_spectrum: 0.9820789
color:
  saturation: 0.5483871
  brandStrength: 0.6091906
  lightness: 0.9951222
  rhythmicContrast: 0.5358423
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
typography_spectrum: 0.06810036
name: RandomThoughts
