collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4527825
  brandStrength: 0.6091906
  lightness: 0.9645869
  rhythmicContrast: 0.4536256
typography_spectrum: 0.06810036
layout_spectrum: 0.06155143
name: RandomThoughts
